### ISSUE TITLE
Null pointer when Ttl is nill

### ISSUE THREAD

**Issue by LCozzoli** [morhaviv/go-fcm-receiver#14]
Some times, the server seems to send messages without Ttl causing crash
![21513941ee5d4a26ab7f4515bd0c9d68](https://github.com/morhaviv/go-fcm-receiver/assets/16455661/81d41335-5761-4dac-8dad-4e76661c3a68)
here
![87b7ab46653b3d38de36cef89730d367](https://github.com/morhaviv/go-fcm-receiver/assets/16455661/b0f34ca3-4fcd-4f1f-9bb3-199fb2e6883c)

**Comment by morhaviv** [comment]
@LCozzoli can you provide an example of the code you're running? I've been using this code for months and never had auch an error.

**Comment by LCozzoli** [comment]
Everything seems to be fixed by its own, it looks like a temporary server error, 

When I added a simple fix for the TTL 
![183437e53e04002b6b35ad3c22de130a](https://github.com/morhaviv/go-fcm-receiver/assets/16455661/cacf87f5-fd02-4fb0-8ff3-c9fdf4558eb0) 

I've got a lot of "invalid salt size" errors causing the function to panic
![05f03da2b848570697ec84b3ca7c5494](https://github.com/morhaviv/go-fcm-receiver/assets/16455661/ffd560b6-568f-4cc7-a6e6-cd2da5cbecae)

After a while, it was back working as usual

This is my code
![1843e944a36a9085b2a79d9b98664818](https://github.com/morhaviv/go-fcm-receiver/assets/16455661/ffb5c1f8-ba9c-4f1d-91e0-33c47583feba)

**Comment by morhaviv** [comment]
Can you see if it seems like this pull request will fix the issue?

**Comment by LCozzoli** [comment]
I'm pulling it, unfortunately I can't seems to be able to reproduce the issue as it seems to be an occasional distant server issue

**Comment by morhaviv** [comment]
@LCozzoli I'm gonna merge it, let's hope it works. BTW, regarding the invalid salt size, does it still happen to you? It used to happen to me in the past and I fixed it somehow, I can't remember how. I think you might be doing something wrong with your tokens, but I'm not sure.

**Comment by LCozzoli** [comment]
@morhaviv Oh no you don't understood, this "decrypt error" happened when I fixed the nill pointer issue but the socket was still sending bad messages

> When I added a simple fix for the TTL
> 
> ![183437e53e04002b6b35ad3c22de130a](https://user-images.githubusercontent.com/16455661/249739984-cacf87f5-fd02-4fb0-8ff3-c9fdf4558eb0.png)
